#!/bin/sh
set -e
if [ "$1" = "configure" ]; then
    udevadm control --reload-rules || true
    udevadm trigger || true
    systemctl daemon-reload || true
    systemctl enable --now idc-daemon.service || true
fi
exit 0
