#!/bin/sh
set -e
if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    systemctl stop idc-daemon.service || true
    systemctl disable idc-daemon.service || true
    systemctl daemon-reload || true
fi
exit 0
